backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blogEn"
    label: "EN - Blog"
    folder: "src/pages/blog"
    format: "frontmatter"
    extension: "en.md"
    #filter:
    #  field: langKey
    #  value: en
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      #- {label: "Lang", name: "langKey", widget: "relation", collection: "langs", searchFields: ["name", "label"], valueField: "name"}
      #- {label: "Language", name: "language", widget: "select", options: [{ value: "ar", label: "Arabic" }, { value: "zh", label: "Chinese" }, { value: "cs", label: "Czech" }, { value: "en", label: "English" }, { value: "vi", label: "Vietnamese" }]}
      - {label: "Language Key", name: "langKey", widget: "hidden", default: "en"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blogPt"
    label: "PT - Blog"
    folder: "src/pages/blog"
    format: "frontmatter"
    extension: "pt.md"
    #filter:
    #  field: langKey
    #  value: en
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      #- {label: "Lang", name: "langKey", widget: "relation", collection: "langs", searchFields: ["name", "label"], valueField: "name"}
      #- {label: "Language", name: "language", widget: "select", options: [{ value: "ar", label: "Arabic" }, { value: "zh", label: "Chinese" }, { value: "cs", label: "Czech" }, { value: "en", label: "English" }, { value: "vi", label: "Vietnamese" }]}
      - {label: "Language Key", name: "langKey", widget: "hidden", default: "pt"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.en.md"
        label: "EN - About"
        name: "about-en"
        fields:
          #- {label: "Lang", name: "langKey", widget: "relation", collection: "langs", searchFields: ["name", "label"], valueField: "name"}
          #- {label: "Language", name: "language", widget: "select", options: [{ value: "ar", label: "Arabic" }, { value: "zh", label: "Chinese" }, { value: "cs", label: "Czech" }, { value: "en", label: "English" }, { value: "vi", label: "Vietnamese" }]}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/about/index.cs.md"
        label: "CS - O nás"
        name: "about-cs"
        fields:
          #- {label: "Lang", name: "langKey", widget: "relation", collection: "langs", searchFields: ["name", "label"], valueField: "name"}
          #- {label: "Language", name: "language", widget: "select", options: [{ value: "ar", label: "Arabic" }, { value: "zh", label: "Chinese" }, { value: "cs", label: "Czech" }, { value: "en", label: "English" }, { value: "vi", label: "Vietnamese" }]}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Obsah", name: "body", widget: "markdown"}

      - file: "src/pages/products/index.en.md"
        label: "EN - Products"
        name: "products-en"
        fields:
          #- {label: "Lang", name: "langKey", widget: "relation", collection: "langs", searchFields: ["name", "label"], valueField: "name"}
          #- {label: "Language", name: "language", widget: "select", options: [{ value: "ar", label: "Arabic" }, { value: "zh", label: "Chinese" }, { value: "cs", label: "Czech" }, { value: "en", label: "English" }, { value: "vi", label: "Vietnamese" }]}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Language Key", name: "langKey", widget: "hidden", default: "en"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta", name: "meta", widget: "string"}
          - label: "Products"
            name: "products-en"
            widget: "list"
            fields:
              - {label: "Product ID", name: "id", widget: "string"}
              - {label: "Title", name: "title", "string"}
              - {label: "Description", name: "description", widget: "markdown"}
              - {label: "Detail", name: "detail", widget: "markdown"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Cloud", name: "cloud", widget: "image"}
              - label: "Info"
                name: "info"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", "string"}
                  - {label: "Expire", name: "expire", "string"}
                  - {label: "Package Weight", name: "packageWeight", "string"}
                  - {label: "Package Size", name: "packageSize", "string"}
                  - {label: "Code", name: "code", "string"}
