backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog-cs"
    label: "CS - Blog"
    folder: "src/pages/blog"
    format: "frontmatter"
    extension: "cs.md"
    #filter:
    #  field: langKey
    #  value: cs
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Language Key", name: "langKey", widget: "hidden", default: "cs"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog-en"
    label: "EN - Blog"
    folder: "src/pages/blog"
    format: "frontmatter"
    extension: "en.md"
    #filter:
    #  field: langKey
    #  value: en
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Language Key", name: "langKey", widget: "hidden", default: "en"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/products/index.zh.md"
        label: "ZH - Products"
        name: "zh-products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Language Key", name: "langKey", widget: "hidden", default: "zh"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta", name: "meta", widget: "string"}
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Product ID", name: "id", widget: "string"}
              - {label: "Title", name: "title", "string"}
              - {label: "Description", name: "description", widget: "markdown"}
              - {label: "Detail", name: "detail", widget: "markdown"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Cloud", name: "cloud", widget: "image"}
              - label: "Info"
                name: "info"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", "string"}
                  - {label: "Expire", name: "expire", "string"}
                  - {label: "Package Weight", name: "packageWeight", "string"}
                  - {label: "Package Size", name: "packageSize", "string"}
                  - {label: "Code", name: "code", "string"}

      - file: "src/pages/about/index.zh.md"
        label: "ZH - About"
        name: "zh-about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/products/index.vi.md"
        label: "VI - Products"
        name: "vi-products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Language Key", name: "langKey", widget: "hidden", default: "vi"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta", name: "meta", widget: "string"}
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Product ID", name: "id", widget: "string"}
              - {label: "Title", name: "title", "string"}
              - {label: "Description", name: "description", widget: "markdown"}
              - {label: "Detail", name: "detail", widget: "markdown"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Cloud", name: "cloud", widget: "image"}
              - label: "Info"
                name: "info"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", "string"}
                  - {label: "Expire", name: "expire", "string"}
                  - {label: "Package Weight", name: "packageWeight", "string"}
                  - {label: "Package Size", name: "packageSize", "string"}
                  - {label: "Code", name: "code", "string"}

      - file: "src/pages/about/index.vi.md"
        label: "VI - About"
        name: "vi-about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/products/index.en.md"
        label: "EN - Products"
        name: "en-products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Language Key", name: "langKey", widget: "hidden", default: "en"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta", name: "meta", widget: "string"}
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Product ID", name: "id", widget: "string"}
              - {label: "Title", name: "title", "string"}
              - {label: "Description", name: "description", widget: "markdown"}
              - {label: "Detail", name: "detail", widget: "markdown"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Cloud", name: "cloud", widget: "image"}
              - label: "Info"
                name: "info"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", "string"}
                  - {label: "Expire", name: "expire", "string"}
                  - {label: "Package Weight", name: "packageWeight", "string"}
                  - {label: "Package Size", name: "packageSize", "string"}
                  - {label: "Code", name: "code", "string"}

      - file: "src/pages/about/index.en.md"
        label: "EN - About"
        name: "en-about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/products/index.cs.md"
        label: "CS - Products"
        name: "cs-products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Language Key", name: "langKey", widget: "hidden", default: "cs"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta", name: "meta", widget: "string"}
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Product ID", name: "id", widget: "string"}
              - {label: "Title", name: "title", "string"}
              - {label: "Description", name: "description", widget: "markdown"}
              - {label: "Detail", name: "detail", widget: "markdown"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Cloud", name: "cloud", widget: "image"}
              - label: "Info"
                name: "info"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", "string"}
                  - {label: "Expire", name: "expire", "string"}
                  - {label: "Package Weight", name: "packageWeight", "string"}
                  - {label: "Package Size", name: "packageSize", "string"}
                  - {label: "Code", name: "code", "string"}

      - file: "src/pages/about/index.cs.md"
        label: "CS - O nás"
        name: "cs-about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Obsah", name: "body", widget: "markdown"}

      - file: "src/pages/products/index.ar.md"
        label: "AR - Products"
        name: "ar-products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Language Key", name: "langKey", widget: "hidden", default: "ar"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta", name: "meta", widget: "string"}
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Product ID", name: "id", widget: "string"}
              - {label: "Title", name: "title", "string"}
              - {label: "Description", name: "description", widget: "markdown"}
              - {label: "Detail", name: "detail", widget: "markdown"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Cloud", name: "cloud", widget: "image"}
              - label: "Info"
                name: "info"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", "string"}
                  - {label: "Expire", name: "expire", "string"}
                  - {label: "Package Weight", name: "packageWeight", "string"}
                  - {label: "Package Size", name: "packageSize", "string"}
                  - {label: "Code", name: "code", "string"}

      - file: "src/pages/about/index.ar.md"
        label: "AR - About"
        name: "ar-about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
